language: python
python:
  - "3.4"
cache:
  - pip
before_install:
    - sudo apt-get update -q
    - sudo apt-get build-dep python-numpy python-matplotlib python-scipy -y
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r requirements_doc.txt
    - pip install sip_models
    - pip install geccoinv
    - python setup.py install
# command to run tests
script: sh travis_test.sh
# not used, but could be interesting:
# https://docs.travis-ci.com/user/deployment/pages/
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    mkdir ghpages
    cd ghpages
    git clone --depth=2 --branch=gh-pages https://github.com/m-weigand/ccd_tools.git
    rm -r ccd_tools/doc_ccd/
    cp -r ../docs/doc/_build/html/ ccd_tools/doc_ccd
    git status
    # This generates a `web` directory containing the website.
    # make web
    # cd web
    # git init
    # git checkout -b gh-pages
    # git add .
    # git -c user.name='travis' -c user.email='travis' commit -m init
    # # Make sure to make the output quiet, or else the API token will leak!
    # # This works because the API key can replace your password.
    # git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/<myrepo>-gh-pages gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
